export default {
  ACCOUNT: "ACCOUNT",
  LOGIN: "LOGIN",
  PASSWORD: "PASSWORD",
  ARTICLE: "ARTICLE",
  ARTICLE_ALL: "ARTICLE_ALL",
  ARTICLE_CREATE: "ARTICLE_CREATE",
  ARTICLE_UPDATE: "ARTICLE_UPDATE",
  CONTACTS: "CONTACTS",
  CONTACTS_ALL: "CONTACTS_ALL"
};
